### PR TITLE
Winlauncher improvement for simpler launchers

### PR DESCRIPTION
**Pull request by chrisjbillington**
Punchline at the end:

1. This PR makes `winlauncher` a top-level module (i.e. not a submodule of labscript_utils) with a `main()` function, so that it can be imported without importing anything else from `labscript_utils` and its functionality used upon import instead of only as running it as a script. Previously it has been run directly as a script and not imported - avoiding a `labscript_utils` import is important since non-pure-python code may not function prior to a conda environment being activated, so this module needs to be pretty standalone.

2. It modifies winlauncher so that rather than requiring you to pass it a conda env name and prefix, it introspects these based on the path of the Python interpreter it is run with (needs to be tested but I'm pretty sure the idea is sound).

3. It also modifies winlauncher to inspect `sys.argv[0]`, and if it finds that it is anything other than `__file__` (i.e. the path to `winlauncher.py`), it realises that - it is being called from an [`entry_point` script](https://packaging.python.org/specifications/entry-points/)! It then uses a naming convention whereby it assumes that the entry point script's name (which is in sys.arv[0]) is a module name (Or, if running under pythonw, a module name with an added 'w' suffix), and it runs that module's `__main__.py` as a script (or the module file itself if it's a standalone module not in a package). 

Punchline is that with these changes, runmanager can add the following to `setup()` in its `setup.py`:
```python
entry_points={
        'console_scripts': ['runmanager = winlauncher:main'],
        'gui_scripts': ['runmanagerw = winlauncher:main'],
    },
```

and bam - runmanager .exe's in the Scripts folder:

Peek 2020-05-02 23-04

These executables know which Python interpreter to use already, and to run winlauncher. That Python interpreter knows where winlauncher is already. And winlauncher can work out where the module it needs to run is, without any extra command line arguments.

This will make the shortcuts a bit simpler - they'll just be a path to a single exe like most shortcuts are in Windows, instead of this list of 3 fairly nested absolute paths that can exceed some kind of length limit that was seen in labscript-suite/runmanager#73

Work yet to do is make AppID stuff use this - should be pretty simple.

### CODE REVIEW

**Comment by philipstarkey** [comment]
I'd like to have a closer look before you merge. Might not get to it today so can you wait at least 36 hours before merging?

**Comment by chrisjbillington** [comment]
No worries. Also happy to test the conda stuff and get the appID functions using this before merging. But I'm happy either way.

**Comment by philipstarkey** [comment]
So two questions so far:

1. Does this work under Linux in the same way?

2. Does this need to be in the labscript utils repo or is it possible to split it out into its own package on PyPI? Could such a package also contain the winshell code? I've been thinking such code is likely useful for other projects as I have yet to see Python apps get this sort of thing working perfectly on Windows.

**Comment by chrisjbillington** [comment]
Under linux having a launcher at all is not as necessary, but would still be nice. And I might as well so that the setup.py's don't have to have an if statement in there for whether to make the launchers.

Right now it'll probably just crash since it is making windows specific assumptions like executables ending in 'exe' and passing a windows-specific flag to subprocess.Popen.

To make it work on unix I can have winlauncher check if not on windows, and if so ignore the conda stuff and just do `runpy.run_path` to execute the script instead of a subprocess.

Then probably rename it so it doesn't have 'win' in the name.

Happy to consider forking it off into a separate project, maybe as I'm working on it now, or maybe once it's working. Since winlauncher it's a top-level module, doing so would be backward compatible - labscript_utils would just depend on it, and could import the relevant functions into labscript_utils.winshell for backward compat.

As I'm hacking on winshell in the next few days, I'll keep this in mind and see if it is sensible to keep it general and if anything comes up that would prevent that. If it looks sensible to branch it off, we could do it right away. I've been intending to extend winshell to create linux launchers as well (as in the equivalent of shortcuts, that integrate with OS menus), and to look into how to do that sort of thing on macos too. Could be a sensible thing to wrap up all in one project.

**Comment by chrisjbillington** [comment]
Ok, so I am in the process of breaking this out into a separate project. It's coming along nicely. The Windows userappmodel_id setting can be done a bit more simply by calling `SetCurrentProcessExplicitAppUserModelID` to associate all windows from the process with an existing shortcut, rather than having to call it on each window separately. So that simplifies the Qt code a bit. I also have the Linux equivalent working properly, which is a long time coming.

For mac I don't know how to create the equivalent of shortcuts, so that will need more research - maybe have to look at the conda spyder package's postinstall script.

**Comment by chrisjbillington** [comment]
Closing this since it is superseded by the broken-out [desktop-app](https://github.com/chrisjbillington/desktop-app) package.

We should instead add deprecation warnings to winshell or winlauncher and remove them at some point.

**Pull request closed without merging**
